### PR TITLE
Revise license documentation

### PR DESCRIPTION
**Pull request by dolph**

### CODE REVIEW

**Review by mlangbehn — DISMISSED** [review]
Why are we making this change?

**Comment by dolph** [comment]
My apologies for not entering a description (I opened a *lot* of similar PR's!). I'm standardizing the `LICENSE` file across all of our journey repositories to exactly match [the license file produced by GitHub's licensing tool](https://github.com/dolph/license-test). In many cases, our license files just contained random copy/paste issues (such as extra whitespace, broken indentation, missing a newline at the end of the file, etc). In other cases, license files were missing altogether, or were not licensed correctly. However, in this case, it looks like a relatively inconsequential change (perhaps the defacto Apache license switched from curly braces to brackets since this file was created). I'd still appreciate merging this, though, just so our repositories are one step closer to being consistent with each other.

**Review by stevemar — DISMISSED** [review]
the failing CI is unrelated, we can still merge this

**Review by loafyloaf — APPROVED** [review]
lgtm

**Pull request merged**
